  reporting: "off"
  startuppopupversion: 1

  gui:
    # stuff relating to the UI
    scrollHeight: 2 # how many lines you scroll by
    scrollPastBottom: true # enable scrolling past the bottom
    sidePanelWidth: 0.3333 # number from 0 to 1
    theme:
      lightTheme: false # For terminals with a light background
      activeBorderColor:
        - yellow
        - bold
      inactiveBorderColor:
        - cyan
      optionsTextColor:
        - yellow
      selectedLineBgColor:
        - black
      selectedRangeBgColor:
        - blue
    commitLength:
      show: true
    mouseEvents: true
    skipUnstageLineWarning: false
    skipStashWarning: true
  git:
    paging:
      colorArg: always
      pager: delta --syntax-theme Dracula --plus-style 'syntax "#003800"' --minus-style 'syntax "#3f0001"' --features 'line-numbers decorations' --color-only | sed 's/\[0\;K//g'
    branchLogCmd: "git log --graph --pretty='%C(bold yellow)%h%Creset - %Cgreen(%cr)%C(auto)%d%Creset %s %C(bold blue)<%an>%Creset' --color=always {{branchName}}"
  update:
    method: prompt # can be: prompt | background | never
    days: 14 # how often an update is checked for
